#!/bin/sh

CC=/opt/clang/bin/clang
SYSROOT=/havana/binaries/linaro-arm-linux-gnueabihf-4.9
TARGET=armv7-unknown-linux-gnueabihf
STATIC_LINK="-static -static-libgcc"
CFLAGS="-mfloat-abi=hard -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16"

if [[ "$@" == *-c* ]] || [[ "$@" == *-S* ]]
then
    STATIC_LINK=
fi

$CC -target $TARGET $CFLAGS --sysroot=$SYSROOT $STATIC_LINK "$@"
