#!/bin/sh

CC=/opt/clang/bin/clang++
SYSROOT=/havana/binaries/linaro-arm-linux-gnueabihf-4.9
TARGET=armv7-unknown-linux-gnueabihf
CFLAGS="-mfloat-abi=hard -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16"

$CC -target $TARGET $CFLAGS --sysroot=$SYSROOT "$@"
