#!/bin/sh

set -euo pipefail

# Doesn't seem to be used anymore 29.08.2020
# IFS="."; read day month year <<<$1

curl -N -s https://www.deutschepost.de/sendung/simpleQueryResult.html \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -H 'Referer: https://www.deutschepost.de/sendung/simpleQuery.html' \
        --data "form.sendungsnummer=$1" \
        --data "form.einlieferungsdatum_tag=" \
        --data "form.einlieferungsdatum_monat=" \
        --data "form.einlieferungsdatum_jahr=" | grep -m1 -E "Die Sendung|zur Sendung|Einlieferungsdatum|nicht vorgenommen" \
        | sed 's/^  *//g' | sed -e 's/<[^>]*>//g' | recode html..UTF-8
