#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: $(basename $0) <pass name>"
    exit 1
fi

platform=`uname -s`
case $platform in
    CYGWIN*)
        FILE_PATH=`cygpath -w ~/`
    ;;
    Linux*)
        FILE_PATH="$HOME/"
    ;;
esac

FILE_PATH="$FILE_PATH".$1"_pass"

if [ -e $FILE_PATH ]; then
    gpg -d $FILE_PATH
else
    echo "$FILE_PATH does not exist."
    exit 1
fi

