#!/bin/sh
set -eu

HOST_IP=$1
DATE_STRING=$(echo $(date +"%a %b %d %Y %H:%M:%S GMT%z (Central European Summer Time)") | sed s,' ','%20',g)
DEST=/tmp/ipmi-$HOST_IP.jpeg
USERNAME=ADMIN
PASSWORD=ADMIN

function login {
  curl -s -L 'https://'$HOST_IP'/cgi/login.cgi' \
    --cookie ~/.ikvmview.txt \
    --cookie-jar ~/.ikvmview.txt \
    -H 'Connection: keep-alive' \
    -H 'Cache-Control: max-age=0' \
    -H 'Upgrade-Insecure-Requests: 1' \
    -H 'Origin: https://149.44.161.29:34121' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
    -H 'Sec-Fetch-Site: same-origin' \
    -H 'Sec-Fetch-Mode: navigate' \
    -H 'Sec-Fetch-User: ?1' \
    -H 'Sec-Fetch-Dest: document' \
    -H 'Referer: https://149.44.161.29:34121/' \
    -H 'Accept-Language: de,en-US;q=0.9,en;q=0.8,tr;q=0.7' \
    --data-raw 'name='$USERNAME'&pwd='$PASSWORD \
    --compressed \
    --insecure &> /dev/null && echo "Logged in."
}

function getscreen {
    # First ask for a refresh
    curl -s "https://$HOST_IP/cgi/CapturePreview.cgi" \
      --cookie "~/.ikvmview.txt" \
      -H 'Connection: keep-alive' \
      -H 'Accept: text/javascript, text/html, application/xml, text/xml, */*' \
      -H 'X-Prototype-Version: 1.5.0' \
      -H 'X-Requested-With: XMLHttpRequest' \
      -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
      -H 'Content-type: application/x-www-form-urlencoded; charset=UTF-8' \
      -H "Origin: $HOST_IP" \
      -H 'Sec-Fetch-Site: same-origin' \
      -H 'Sec-Fetch-Mode: cors' \
      -H 'Sec-Fetch-Dest: empty' \
      -H "Referer: https://$HOST_IP/cgi/url_redirect.cgi?url_name=sys_info" \
      -H 'Accept-Language: de,en-US;q=0.9,en;q=0.8,tr;q=0.7' \
      --data-raw 'IKVM_PREVIEW.XML=(0%2C0)&time_stamp='$DATE_STRING'&_=' \
      --compressed \
      --insecure -o /tmp/ipmi.request &> /dev/null || (echo "Failed to request image." && return 1)

    # Now get the new image
    curl -s "https://$HOST_IP"'/cgi/url_redirect.cgi?url_name=Snapshot&url_type=img&time_stamp='$DATE_STRING \
      --cookie "~/.ikvmview.txt" \
      -H 'Connection: keep-alive' \
      -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
      -H 'Accept: image/webp,image/apng,image/*,*/*;q=0.8' \
      -H 'Sec-Fetch-Site: same-origin' \
      -H 'Sec-Fetch-Mode: no-cors' \
      -H 'Sec-Fetch-Dest: image' \
      -H "Referer: https://$HOST_IP/cgi/url_redirect.cgi?url_name=sys_info" \
      -H 'Accept-Language: de,en-US;q=0.9,en;q=0.8,tr;q=0.7' \
      --compressed \
      --insecure -o $DEST

      grep "File Not Found" $DEST > /dev/null 2>&1 && return 2
}

login
until getscreen
do
    echo "Failed to get the preview image."
    sleep 10s
done

feh --title "PXE View for $HOST_IP" --auto-reload $DEST > /dev/null 2>&1 &

while true; do
    pidof feh &> /dev/null || exit 0
    getscreen
    sleep 5s
done
