#!/bin/zsh
set -eu

HOST_IP=$1
SID=$2
COOKIE='Cookie: langSetFlag=0; language=English; SID='$SID'; mainpage=system; subpage=sys_info'
DATE_STRING=$(echo $(date +"%a %b %d %Y %H:%M:%S GMT%z (Central European Summer Time)") | sed s,' ','%20',g)
DEST=/tmp/ipmi-$HOST_IP.jpeg

function getscreen {
    # First ask for a refresh
    curl -s "https://$HOST_IP/cgi/CapturePreview.cgi" \
      -H 'Connection: keep-alive' \
      -H 'Accept: text/javascript, text/html, application/xml, text/xml, */*' \
      -H 'X-Prototype-Version: 1.5.0' \
      -H 'X-Requested-With: XMLHttpRequest' \
      -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
      -H 'Content-type: application/x-www-form-urlencoded; charset=UTF-8' \
      -H "Origin: $HOST_IP" \
      -H 'Sec-Fetch-Site: same-origin' \
      -H 'Sec-Fetch-Mode: cors' \
      -H 'Sec-Fetch-Dest: empty' \
      -H "Referer: https://$HOST_IP/cgi/url_redirect.cgi?url_name=sys_info" \
      -H 'Accept-Language: de,en-US;q=0.9,en;q=0.8,tr;q=0.7' \
      -H "$COOKIE" \
      --data-raw 'IKVM_PREVIEW.XML=(0%2C0)&time_stamp='$DATE_STRING'&_=' \
      --compressed \
      --insecure &> /dev/null || (echo "Failed to request image." && exit 1)

    # Now get the new image
    curl -s "https://$HOST_IP"'/cgi/url_redirect.cgi?url_name=Snapshot&url_type=img&time_stamp='$DATE_STRING \
      -H 'Connection: keep-alive' \
      -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
      -H 'Accept: image/webp,image/apng,image/*,*/*;q=0.8' \
      -H 'Sec-Fetch-Site: same-origin' \
      -H 'Sec-Fetch-Mode: no-cors' \
      -H 'Sec-Fetch-Dest: image' \
      -H "Referer: https://$HOST_IP/cgi/url_redirect.cgi?url_name=sys_info" \
      -H 'Accept-Language: de,en-US;q=0.9,en;q=0.8,tr;q=0.7' \
      -H "$COOKIE" \
      --compressed \
      --insecure -o $DEST
}

getscreen
feh --title "PXE View for $HOST_IP" --auto-reload $DEST&

while true; do
    pidof feh &> /dev/null || exit 0
    getscreen
    sleep 5s
done
