#!/bin/bash

CHARACTER_SET="[:alnum:]!\"#$%&\'\(\)*+,-./:;<=>?@[\]^_\`{\|}~"
LENGTH=30

[[ ! -z $1 ]] && LENGTH=$1
[[ ! -z $2 ]] && CHARACTER_SET=$2

for i in {1..20}; do
    < /dev/urandom LC_ALL=C tr -dc $CHARACTER_SET | head -c$LENGTH; echo
done
