#!/bin/bash
set -euo pipefail

if [[ -z "$1" ]]; then
  echo "Usage: $0 <hostname> [port]"
  exit 1
fi

echo |
openssl s_client -showcerts -servername "$1" -connect "$1:${2:-443}" 2>/dev/null |
openssl x509 -inform pem -noout -text