#!/usr/bin/python3
# -*- coding: utf-8 -*-

import click
import os


@click.command()
@click.option("--audio-bitrate",
              default="384k",
              help="Requested audio bitrate, default 384k")
@click.option("--audio-codec",
              default="libfdk_aac",
              help="Requested audio codec, default libfdk_aac")
@click.option("--video-bitrate",
              required=True,
              type=str,
              help="Requested video bitrate, e.g 10M")
@click.option("--sample", is_flag=True, help="Do a test 60 seconds encoding.")
@click.option("--sample-start",
              type=str,
              default="05:00:00",
              help="Starting point for the sample, default 05:00:00")
@click.option("--sample-length",
              type=str,
              default="60",
              help="Length of encoding sample in seconds, default 60")
@click.option("--subtitle",
              multiple=True,
              help="External subtitles to be included")
@click.option("--sub-index",
              required=True,
              type=int,
              help="Selected subtitle index")
@click.option("--picture",
              is_flag=True,
              default=False,
              help="The subtitle is picture based (sub, sup, ...)")
@click.option("--font-name",
              default="Tahoma",
              help="Font for text subtitles, default is Tahoma")
@click.option("--film", required=True, help="File to encode")
@click.option("--output", required=True, help="Output file")
def encode(audio_bitrate, audio_codec, video_bitrate, sample, sample_start,
           sample_length, subtitle, sub_index, picture, font_name, film,
           output):

    command_pass1 = ["ffmpeg", "-hide_banner"]
    command_pass2 = ["ffmpeg", "-hide_banner"]

    if sample:
        # Need to put -ss before -i for fast seeking
        command_pass1.extend(["-ss", sample_start])
        command_pass2.extend(["-ss", sample_start])

    command_pass1.extend(["-i", f"\"{film}\""])
    command_pass2.extend(["-i", f"\"{film}\""])

    if sample:
        command_pass1.extend(["-t", sample_length])
        command_pass2.extend(["-t", sample_length])

    codec_parameters = [
        "-map", "0:v", "-map", "0:a", "-c:v", "libx264", "-tune", "film",
        "-crf", "18", "-profile:v", "high", "-level", "4.2", "-b:v",
        video_bitrate
    ]

    if not picture and (len(subtitle) > 1):
        print("You can only select one text subtitle.")
        sys.exit(-1)

    if picture:
        for sub in subtitle:
            command_pass1.extend(["-i", f"\"{sub}\""])
            command_pass2.extend(["-i", f"\"{sub}\""])

        for command in [command_pass1, command_pass2]:
            command.extend(
                ["-filter_complex",
                 "[0:v][%d:s]overlay" % sub_index])
    else:
        if len(subtitle):
            subfile = subtitle[0]
        else:
            subfile = film

        command_pass1.extend([
            "-vf",
            f"subtitles=\"{subfile}\":si={sub_index}:force_style='FontName={font_name}'"
        ])

        command_pass2.extend([
            "-vf",
            f"subtitles=\"{subfile}\":si={sub_index}:force_style='FontName={font_name}'"
        ])

    command_pass1.extend(codec_parameters)
    command_pass2.extend(codec_parameters)

    command_pass1.extend(
        ["-an", "-nostdin", "-pass", "1", "-f", "rawvideo", "-y", "/dev/null"])

    command_pass2.extend([
        "nostdin", "-pass", "2", "-y", "-c:a", audio_codec, "-b:a",
        audio_bitrate, f"\"{output}\""
    ])

    with open("pass1.sh", "w") as f:
        f.write(" ".join(command_pass1))
        os.chmod("pass1.sh", 0o755)

    with open("pass2.sh", "w") as f:
        f.write(" ".join(command_pass2))
        os.chmod("pass2.sh", 0o755)


if __name__ == "__main__":
    encode()
