#!/bin/zsh
set -eu

common_flags=(
    -O3
    -Wall
    -Wextra
    -pedantic
    -pthread
    -fno-omit-frame-pointer
)

common_c_flags=(
    -std=c11
)

common_cxx_flags=(
    -std=c++14
)

clang_flags=(
    -Wl,-rpath=/opt/clang/lib64
    -fuse-ld=lld
)

gcc_flags=(
    -fuse-ld=gold
)

icc_flags=(
    -fuse-ld=gold
    -Wl,-rpath,/havana/intel/compilers_and_libraries_2016.3.210/linux/bin/intel64
    -Wl,-rpath,/havana/intel/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64_lin
)

[[ -z ${1:-} ]] && echo "Please pass a compiler: clang, gcc, icc" && exit 0

echo -n "$common_flags "

case "${2:-}" in
    c)
        echo -n "$common_c_flags "
        ;;
    *)
        echo -n "$common_cxx_flags "
        ;;
esac

case "$1" in
    gcc)
        echo $gcc_flags
        ;;
    clang)
        echo $clang_flags
        ;;
    icc)
        echo $icc_flags
        ;;
    *)
        echo "$1 is not a known compiler."
        exit 1
        ;;
esac
