#!/usr/bin/env zsh
set -euo pipefail

temp=$(mktemp --suffix=.fs)
output=${temp:t:r}.exe
echo "module Program" > $temp
cat /dev/stdin >> $temp
fsharpc --nologo --utf8output $temp
./$output
rm -f $temp $output
