#!/usr/bin/env zsh

if [ -z $1 ]; then
    echo "Usage: ${0:t} <pass name>"
fi

FILE_PATH="$HOME/.$1_pass"

if [ -d /cygdrive ]; then
    FILE_PATH=$(cygpath -u $FILE_PATH)
fi

if [ -e $FILE_PATH ]; then
    if [[ "$(head -n1 $FILE_PATH)" = "-----BEGIN PGP MESSAGE-----" ]]; then
        gpg -d $FILE_PATH
    else
        cat $FILE_PATH
    fi
else
    echo "$FILE_PATH does not exist."
fi

