#!/usr/bin/env zsh

if [ -z $1 ]; then
    echo "Usage: ${0:t} <pass name>"
    exit 1
fi

FILE_PATH="$HOME/.$1_pass"

if [ -e $FILE_PATH ]; then
    if grep -q "BEGIN PGP MESSAGE" $FILE_PATH; then
        gpg -d $FILE_PATH(+cyg)
    else
        cat $FILE_PATH
    fi
else
    echo "$FILE_PATH does not exist."
    exit 1
fi

