#!/usr/bin/env zsh

NEWFILE=/tmp/mutt_bak_${1:t}
rm ${NEWFILE} -f

cp $1 ${NEWFILE} 1>/dev/null 2>&1

if [ -z $COMSPEC ]; then
    xdg-open ${NEWFILE} &> /dev/null
else
    start $(cygpath -w ${NEWFILE})
fi
