#!/usr/bin/env zsh

NEWFILE=/tmp/mutt_bak_$((RANDOM))_${1:t}
rm ${NEWFILE} -f

cp $1 ${NEWFILE} 1>/dev/null 2>&1

if [ -z $COMSPEC ]; then
    xdg-open ${NEWFILE} &> /dev/null
else
    cygstart ${NEWFILE}
fi
