#!/bin/sh

url="http://translate.google.com/translate_tts?tl="
userAgent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2438.3 Safari/537.36"
lang=$1
query=${@:2}

curl -s -A "$userAgent" --data-urlencode "q=$query" "$url$lang" | mpv - &> /dev/null
