#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Please enter a command."
    exit
fi

if [ -z "$(pidof spotify)" ]; then
  echo "Spotify is not running."
  exit
fi

call_spotify() {
    dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 $@ > /dev/null
}

case $1 in
    "play")
        call_spotify org.mpris.MediaPlayer2.Player.PlayPause
        ;;
    "pause")
        call_spotify org.mpris.MediaPlayer2.Player.Pause
        ;;
    "stop")
        call_spotify org.mpris.MediaPlayer2.Player.Stop
        ;;
    "next")
        call_spotify org.mpris.MediaPlayer2.Player.Next
        ;;
    "prev")
        call_spotify org.mpris.MediaPlayer2.Player.Previous
        ;;
    "playURL")
        call_spotify org.mpris.MediaPlayer2.Player.OpenUri string:$2
        ;;
    *)
        echo "Unknown command: " $1
        ;;
esac
