#!/usr/bin/env zsh
set -euo pipefail

TARGET=x86_64-w64-mingw32
WINDOWS_TARGET=0x0603

if [ ! -z ${WINDIR:-} ]; then
    GCC_VERSION=6.0.0
    GCC_ROOT=C:/mingw-w64-$GCC_VERSION
    PATH=$(cygpath -u $GCC_ROOT)/bin:$PATH
else
    PATH=/opt/clang/bin:$PATH
fi

COMMON_ARGS+=(-target $TARGET -DWINVER=$WINDOWS_TARGET -D_WIN32_WINNT=$WINDOWS_TARGET -static)
COMMON_C_ARGS=(-static-libgcc)
COMMON_CXX_ARGS=(-static-libstdc++ $COMMON_C_ARGS)

case $0 in
    *-clang)
        clang -std=c11 $COMMON_ARGS $COMMON_C_ARGS "$@"
        ;;
    *-clang++)
        clang++ -std=c++14 $COMMON_ARGS $COMMON_CXX_ARGS "$@"
        ;;
    *)
        echo "Unknown command ${0:t}"
        ;;
esac
