#!/usr/bin/env zsh
set -euo pipefail

TARGET=x86_64-w64-mingw32
WINDOWS_TARGET=0x0603

if (( ! $+commands[$TARGET-gcc] )); then
    echo "Make sure $TARGET-gcc is in PATH"
    exit 1
fi

COMMON_ARGS+=(-target $TARGET -DWINVER=$WINDOWS_TARGET -D_WIN32_WINNT=$WINDOWS_TARGET -static)

case $0 in
    *-clang)
        clang -std=c11 $COMMON_ARGS "$@"
        ;;
    *-clang++)
        clang++ -std=c++14 $COMMON_ARGS "$@"
        ;;
    *)
        echo "Unknown command ${0:t}"
        ;;
esac
