#!/usr/bin/env zsh
set -euo pipefail

TARGET=x86_64-w64-mingw32
WINDOWS_TARGET=0x0603

if [ ! -z ${WINDIR:-} ]; then
    GCC_ROOT=C:/mingw-w64-5.1.1
    GCC_VERSION=5.1.1
    PATH=$(cygpath -u $GCC_ROOT)/bin:$PATH
    C_INCLUDE_PATH=$GCC_ROOT/$TARGET/include
    CXX_INCLUDE_PATH=$GCC_ROOT/include/c++/$GCC_VERSION
else
    GCC_ROOT=/usr/lib64/gcc
    GCC_VERSION=5.1.0
    C_INCLUDE_PATH="/usr/$TARGET/sys-root/$TARGET/include"
    CXX_INCLUDE_PATH="$GCC_ROOT/$TARGET/$GCC_VERSION/include/c++"
    PATH=/opt/clang/bin:$PATH
fi

COMMON_ARGS=(-target $TARGET -DWINVER=$WINDOWS_TARGET -D_WIN32_WINNT=$WINDOWS_TARGET -static)

case $0 in
    *-clang)
        clang -std=c11 $COMMON_ARGS \
              -isystem $C_INCLUDE_PATH "$@"
        ;;
    *-clang++)
        clang++ -std=c++14 $COMMON_ARGS \
                -isystem $C_INCLUDE_PATH \
                -isystem $CXX_INCLUDE_PATH \
                -isystem $CXX_INCLUDE_PATH/$TARGET "$@"
        ;;
    *)
        echo "Unknown command ${0:t}"
        ;;
esac
