#!/bin/sh

SYSROOT=/havana/binaries/linaro-arm-linux-gnueabihf-4.9
TARGET=armv7a-unknown-linux-gnueabihf
CFLAGS="-mfloat-abi=hard -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fuse-ld=gold"

case $0 in
    *clang)
        CC=/opt/clang/bin/clang
        ;;
    *clang++)
        CC=/opt/clang/bin/clang++
        ;;
esac

$CC -target $TARGET $CFLAGS --sysroot=$SYSROOT "$@"
